### ISSUE TITLE
can't install clients: npm prompts for password

### ISSUE THREAD

**Issue by davepacheco** [restify/clients#12]
I'm trying to use this repo from another project, but when I try to "npm install" that project, npm prompts for a password.  I think it's because of this dependency in node-restify-clients:
https://github.com/restify/clients/blob/master/package.json#L66

I can reproduce this myself on my test system:

```
$ npm install git+https://git@github.com/restify/errors.git#master
\assword: -
```

and it just hangs there (with the spinny spinning).  If I hit enter a few times, it actually works.  But this is breaking an automated build environment.

This appears to be the problem described here:
http://stackoverflow.com/questions/19107160/why-is-npm-asking-for-a-password
https://github.com/npm/npm/issues/3956

**Comment by davepacheco** [comment]
It may be just the "git@" in the https URL, which presumably isn't necessary.

**Comment by davepacheco** [comment]
I've confirmed that without the "git@", it works:

```
$ npm install git+https://github.com/restify/errors.git#master
restify-errors@3.0.0 node_modules/restify-errors
├── assert-plus@0.1.5
├── verror@1.6.0 (extsprintf@1.2.0)
└── lodash@3.10.1
```

This is on Node 0.10.40.  I don't see this with Node 0.12.

It would be great to get an updated version of the restify-clients package published with this change.

**Comment by micahr** [comment]
Sorry about that Dave. We'll get that fixed right away.

**Comment by micahr** [comment]
You can now use v1.1.1 which now uses versions instead of git urls.

**Comment by davepacheco** [comment]
Thanks for the super quick fix!
