### ISSUE TITLE
JSON client ignores `accept` option

### ISSUE THREAD

**Issue by retrohacker** [restify/clients#127]
#### Note from maintainer

> This is being migrated here from the restify/node-restify repo https://github.com/restify/node-restify/issues/773

#### Original Issue Body

The [documentation](http://mcavage.me/node-restify/#jsonclient) states that the JSON client can be initialized with an `accept` option that will set the value of the `accept` header. As far as I can tell, it is being ignored.

Here is my test case:
### server

``` javascript
var restify = require('restify');

// initialize server
var server = restify.createServer({
  name    : 'restify-debug',
  version : '0.0.1',
});

server.get('/', function (req, res, next) {
  console.log(req.headers);
  res.send(200);
  return next();
});

// start the server
server.listen(1337, function () {
  console.log('%s listening at %s', server.name, server.url);
});
```
### client

``` javascript
var restify = require('restify');

// initialize the JSON client
var client = restify.createJsonClient({
  url    : 'http://localhost:1337',
  accept : 'application/vnd.chrisallenlane.restify.v1.0.0+json',
});

client.get('/', process.exit);
```

The value of the `accept` header being logged to my console is `"application/json"`.

Contrast that with curl:

``` sh
curl http://localhost:1337 -H 'accept: foo'
```

The value of the `accept` header being logged to my console is `"foo"`, which is what I'd expect. That indicates to me that the problem is with the client, and not the server.

I'll note that I tried setting the header value "manually" by initializing the JSON client with a `headers` property, but `headers.accept` was being ignored as well.

This is occurring with `restify` version `2.8.5`.

**Comment by retrohacker** [comment]
cc @chrisallenlane

**Comment by viniciuskneves** [comment]
I've opened a PR related to this issue: https://github.com/restify/clients/pull/142

**Comment by DonutEspresso** [comment]
Looks like this was merged - closing. Thanks again @viniciuskneves!
