### ISSUE TITLE
JsonClient doesn't allow strings as body

### ISSUE THREAD

**Issue by rluba** [restify/clients#138]
Trying to send a body that consists solely of a string causes JsonClient to throw [because it asserts that the body must be an object.](https://github.com/restify/clients/blob/bbdeb79442a0b79bf55a788b0a409a0b5dc9cc84/lib/JsonClient.js#L41)

But strings are valid JSON payload. They can be serialized to and deserialized from JSON transparently. The whole request passes just fine if I remove over-stringent assertion.

I believe the assertion should be relaxed to allow all valid JSON root types:`string`, `boolean`, `number`, `array` and `object`. (Did I forget something?)

**Comment by DonutEspresso** [comment]
Yep, you're right, seems to be documented as such in the RFC as well.

```
const val = 'foobar';
assert.equal(JSON.parse(JSON.stringify(val)), val)
```

Thanks for reporting this!
