### ISSUE TITLE
dtrace-provider dependency inadvertently removed by #101

### ISSUE THREAD

**Issue by melloc** [restify/clients#168]
In #101 (acadfc4c), the `"dtrace-provider"` dependency was moved into an `"optionalDependency"` field. The correct name for the field is `"optionalDependencies"`. I'll submit a PR against master, but I'd also like to get this backported to a `1.5.3` release if possible.

**Comment by trentm** [comment]
- published restify-clients@2.0.2 with this fix
- created a 1.x maint branch off of commit bbdeb79 (as suggested in #169)
- published restify-clients@1.5.3 with this fix as well

```
$ npm info restify-clients dist-tags
{ latest: '2.0.2', 'latest-1': '1.5.3' }
```
