### ISSUE TITLE
Client side support

### ISSUE THREAD

**Issue by gRoberts84** [restify/clients#17]
Hi there,

I've been trying to wrap my head around this for 3 hours now, thinking it was something I was doing wrong, however... 

Am I right in thinking that the restify-clients is intended for server-to-server communication instead of client-to-server? 

Sorry, I need coffee!

**Comment by DonutEspresso** [comment]
Yes, the "client" is the initiator of the request. So you can use restify-clients to make http requests to other services from within node (like with the [request](https://www.npmjs.com/package/request) module).

**Comment by gRoberts84** [comment]
Hey, thanks for getting back to me.

It was slightly confusing as it appeared as a client to consume the restify
rest service from the client side.

I suppose the package not being in bower should have given that away to me
but I think lack of sleep/coffee clouded that lol.

Thanks

Gav
