### ISSUE TITLE
Follow 3xx redirects

### ISSUE THREAD

**Issue by wagnerfrancisco** [restify/clients#19]
It would be nice to have an option to follow redirects if the original url has returned a 3xx status. What do you think?

**Comment by DonutEspresso** [comment]
Agreed, I think this would a good feature to have.

**Comment by wagnerfrancisco** [comment]
Cool. I'm already working on this, I'll open a PR soon.

**Comment by DonutEspresso** [comment]
Awesome, thank you!

**Comment by DonutEspresso** [comment]
Looks like this has already been merged.
