### ISSUE TITLE
Normalization fail? 

### ISSUE THREAD

**Issue by sebs** [restify/clients#23]
I try to pass a JSON object, containing a array of objects, into restify and it contains an array, this is the result: 

{
  'alarms[0][sensor_id]': 't0',
  'alarms[0][min]': '0',
  'alarms[0][max]': '30',
  'alarms[0][ignore]': 'false',
  'alarms[1][sensor_id]': 't1',
  'alarms[1][min]': '0',
  'alarms[1][max]': '30',
  'alarms[1][ignore]': 'false',
  'alarms[2][sensor_id]': 't2',
  'alarms[2][min]': '0',
  'alarms[2][max]': '30',
  'alarms[2][ignore]': 'false' }

i dont think this is correct

**Comment by micahr** [comment]
Could you provide a bit more context and perhaps a code example?

**Comment by sebs** [comment]
user fail ;) was not a restify issue

**Comment by micahr** [comment]
:+1:
