### ISSUE TITLE
Status code 204 with Content-Length waits for timeout

### ISSUE THREAD

**Issue by mvuherer** [restify/clients#76]
Restify gets stuck on a response with status code 204 and 'Content-Lenght' header valued higher than 0, eventually times out and executes the callback function.

Example server:

```
const http = require('http');

const server = http.createServer((req, res) => {
    const body = 'I\'m gonna go ahead and get you stuck for a bit...';
    console.log(body);
    res.writeHead(204, {
        'Content-Length': Buffer.byteLength(body),
        'Content-Type': 'text/plain',
    });
    res.end(body);
});

server.listen(8000, '127.0.0.1', () => {
    console.log(`Server running ...`);
});
```

Example client:

```
const restify = require('restify');

const client = restify.createJsonClient({
    url: 'http://localhost:8000'
});

const start = new Date().getTime();
client.del('/', () => {
    console.log('Aaand I\'m done... Took me: ', ((new Date().getTime() - start)/1000), 's');
});
```

**Comment by DonutEspresso** [comment]
Hello, thanks for reporting this issue and providing a repro case. That's super helpful. This does appear to be a problem, I'll have to dig into it further to see what's going on. 

I know this isn't particularly helpful, but [RFC7230](https://tools.ietf.org/html/rfc7230#section-3.3.1) does say servers should not send a 204 with a `content-length` header. The safest thing to do in the meantime is to try to avoid this scenario. Even when we fix this in restify-clients, there's no guarantee other types of clients will handle this scenario correctly.

**Comment by mvuherer** [comment]
Thanks for the feedback!

We did resolve it on our side by implementing proper flow  (not sending `content-length` header with 204 status).
If there's anything else I can assist with let me know.
